# Generated by Django 4.2 on 2024-10-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="is_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
