# Generated by Django 4.2 on 2024-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription_is_subscribed"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_price",
            field=models.PositiveIntegerField(
                default=1000, help_text="Стоимость подписки в рублях"
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="content",
        ),
    ]
