# Generated by Django 4.2 on 2024-11-01 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_subscription_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_subscription",
                to="users.subscription",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscription_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
