# Generated by Django 4.2 on 2024-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_subscription_alter_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="subscription",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_subscription",
                to="users.subscription",
            ),
        ),
    ]
