# Generated by Django 4.2 on 2024-11-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscription_price",
            field=models.PositiveIntegerField(
                default=2000, help_text="Стоимость подписки в рублях"
            ),
        ),
    ]
