# Generated by Django 4.2 on 2024-11-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_subscription_subscription_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="subscription_price",
        ),
    ]
