# Generated by Django 4.2 on 2024-10-20 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="is_content_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="content",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя контента",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель контента",
            ),
        ),
    ]
