# Generated by Django 4.2 on 2024-11-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="is_content_paid",
            field=models.BooleanField(
                default=False, verbose_name="Сделать контент платным"
            ),
        ),
    ]
