# Generated by Django 4.2 on 2024-11-01 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_content_is_content_paid_content_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="subscription_price",
        ),
    ]
